### ISSUE TITLE
CRUD Three Table

### ISSUE THREAD

**Issue by SNNafi** [hasancse91/Android-SQLite-Tutorial#1]
How can i crud three table in sqllite.....

**Comment by hasancse91** [comment]
If you know Bengali then please have a look at [this article](https://hellohasan.com/2017/12/29/android-sqlite-database-multiple-tables-crud-operation-tutorial/). I shown here how to use foreign key in relationship between two tables.

I can share a schema diagram for you with three tables. Suppose there are three tables: student, subject and students_taken_sub. Teacher can predefine the subjects. The subject information will be stored in `subject` table. After creating a new student, when teacher want to add any subject for that student, he will make a relation student with subject id. Check this image. Hope you can understand.

<img src="https://i.imgur.com/uEXcqgb.png"  />

**Comment by SNNafi** [comment]
Thanks Hasan Vai 👍

**Comment by hasancse91** [comment]
You are most welcome :-)
