### ISSUE TITLE
how can I add search

### ISSUE THREAD

**Issue by cetrun** [hasancse91/Android-SQLite-Tutorial#2]
how can I add search students?

**Comment by hasancse91** [comment]
Check getStudentByRegistrationNumber(long regNo) method from `DatabaseQueryClass.java` class. You can modify this method if you need to search by name

**Comment by hasancse91** [comment]
Check getStudentByRegistrationNumber(long regNo) method from `DatabaseQueryClass.java` class. You can modify this method if you need to search by name
